color0 #262c26
color1 #fd4663
color2 #a4b5a3
color3 #a3b5a6
color4 #a4b4ab
color5 #b9c6b8
color6 #b8c6bb
color7 #f2f3f2
color8 #636c63
color9 #fd4663
color10 #a4b5a3
color11 #a3b5a6
color12 #a4b4ab
color13 #b9c6b8
color14 #b8c6bb
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1c211c
background            #1c211c
foreground            #f2f3f2
selection_foreground  #b0b5b0
selection_background  #262c26
active_border_color   #a4b5a3
inactive_border_color #262c26
url_color             #a4b5a3

active_tab_foreground   #1c221c
active_tab_background   #a4b5a3
inactive_tab_foreground #b0b5b0
inactive_tab_background #262c26
cursor_trail_color      #b0b5b0
