color0 #111111
color1 #78000e
color2 #007802
color3 #ffffff
color4 #001478
color5 #780068
color6 #00786c
color7 #ffffff
color8 #111111
color9 #78000e
color10 #007802
color11 #ffffff
color12 #001478
color13 #780068
color14 #00786c
color15 #ffffff

cursor                #c0ccbe
cursor_text_color     #111111
background            #111111
foreground            #ededed
selection_foreground  #111111
selection_background  #636363
active_border_color   #c0ccbe
inactive_border_color #191919
url_color             #c0ccbe

active_tab_foreground   #111111
active_tab_background   #c0ccbe
inactive_tab_foreground #a6a6a6
inactive_tab_background #191919
cursor_trail_color      #a6a6a6
