[audio]
enable_overdrive = true
enable_sounds = false
notification_sound = ""
sound_volume = 0.5
volume_change_sound = ""

[backdrop]
blur_intensity = 0.68000000715255737
enabled = false
tint_intensity = 0.0

[bar]
order = [ "default" ]

    [bar.default]
    auto_hide = false
    background_opacity = 1.0
    border = "primary"
    border_width = 0.0
    capsule = false
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 1.0
    capsule_padding = 6.0
    center = [ "workspaces" ]
    contact_shadow = false
    enabled = false
    end = [
        "media",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "session"
    ]
    font_weight = 500
    margin_edge = 10
    margin_ends = 250
    padding = 14
    panel_overlap = 1
    position = "top"
    radius = 0
    radius_bottom_left = 0
    radius_bottom_right = 0
    radius_top_left = 0
    radius_top_right = 0
    reserve_space = true
    scale = 1.0
    shadow = false
    start = [ "wallpaper", "clock", "control-center" ]
    thickness = 34
    widget_spacing = 12

[brightness]
enable_ddcutil = false
ignore_mmids = []

[control_center]
sidebar = "compact"
sidebar_section = "compact"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

[desktop_widgets]
enabled = false
schema_version = 1
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000006"
]

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    cx = 853.5
    cy = 533.5
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        aspect_ratio = 2.5
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    cx = 853.5
    cy = 533.5
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        aspect_ratio = 2.5
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    cx = 853.5
    cy = 533.5
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        aspect_ratio = 2.5
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    cx = 853.5
    cy = 533.5
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        aspect_ratio = 2.5
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    cx = 853.5
    cy = 533.5
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        aspect_ratio = 2.5
        bands = 32
        show_when_idle = true

[dock]
active_monitor_only = false
active_opacity = 1.0
active_scale = 1.0
auto_hide = true
background_opacity = 1.0
enabled = false
icon_size = 42
inactive_opacity = 0.85000002384185791
inactive_scale = 0.85000002384185791
item_spacing = 6
launcher_icon = "grid-dots"
launcher_position = "none"
margin_edge = 8
margin_ends = 0
monitors = []
padding = 8
pinned = []
position = "bottom"
radius = 12
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 12
radius_top_right = 12
reserve_space = false
shadow = false
show_dots = false
show_instance_count = true
show_running = true

[hooks]
battery_low_percent_threshold = 0
battery_state_changed = []
battery_under_threshold = []
bluetooth_disabled = []
bluetooth_enabled = []
colors_changed = []
logging_out = []
power_profile_changed = []
rebooting = []
session_locked = []
session_unlocked = []
shutting_down = []
started = []
theme_mode_changed = []
wallpaper_changed = []
wifi_disabled = []
wifi_enabled = []

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 0.0

    [idle.behavior.lock]
    action = "lock"
    command = ""
    enabled = false
    resume_command = ""
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    command = ""
    enabled = true
    resume_command = ""
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    command = ""
    enabled = true
    resume_command = ""
    timeout = 660

[keybinds]
cancel = [ "Escape" ]
down = [ "Down" ]
left = [ "Left" ]
right = [ "Right" ]
up = [ "Up" ]
validate = [ "Return" ]

[lockscreen]
blur_intensity = 0.5
blurred_desktop = false
tint_intensity = 0.30000001192092896

[nightlight]
enabled = false
force = false
start_time = ""
stop_time = ""
temperature_day = 6500
temperature_night = 4000
use_weather_location = true

[notification]
background_opacity = 1.0
collapse_on_dismiss = true
enable_daemon = true
layer = "top"
monitors = []
offset_x = 20
offset_y = 8
position = "top_right"
scale = 1.0

[osd]
background_opacity = 0.97000002861022949
keyboard_layout = true
lock_keys = true
monitors = []
offset_x = 20
offset_y = 8
orientation = "horizontal"
position = "top_right"
scale = 1.0

[shell]
clipboard_auto_paste = "auto"
clipboard_confirm_clear_history = false
clipboard_enabled = true
clipboard_history_max_entries = 50
clipboard_image_action_command = ""
corner_radius_scale = 0.0
date_format = "%A, %x"
disable_mipmaps = false
font_family = "CaskaydiaMono Nerd Font"
launch_apps_as_systemd_services = true
middle_click_opens_widget_settings = false
niri_overview_type_to_launch_enabled = false
offline_mode = false
password_style = "default"
polkit_agent = true
screen_time_enabled = false
settings_show_advanced = true
shared_gl_context = true
show_location = true
telemetry_enabled = false
time_format = "{:%H:%M}"
ui_scale = 0.80000001192092896

    [shell.animation]
    enabled = false
    speed = 1.0

    [shell.mpris]
    blacklist = []

    [shell.panel]
    background_blur = true
    borders = false
    clipboard_placement = "centered"
    control_center_placement = "centered"
    launcher_categories = false
    launcher_compact = false
    launcher_placement = "centered"
    launcher_show_icons = true
    open_near_click_clipboard = false
    open_near_click_control_center = false
    open_near_click_launcher = false
    open_near_click_session = false
    open_near_click_wallpaper = false
    session_placement = "centered"
    shadow = false
    transparency_mode = "solid"
    wallpaper_placement = "centered"

    [shell.screen_corners]
    enabled = false
    size = 32

    [[shell.session.actions]]
    action = "lock"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "default"

    [shell.shadow]
    alpha = 0.0
    direction = "down_left"

[system.monitor]
cpu_poll_seconds = 3.0
disk_poll_seconds = 10.0
enabled = true
gpu_poll_seconds = 3.0
memory_poll_seconds = 3.0
network_poll_seconds = 3.0

[theme]
builtin = "Noctalia"
community_palette = "Monochrome"
custom_palette = "theme"
mode = "light"
source = "custom"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "kitty", "niri", "qt" ]
    community_ids = [ "obsidian", "zed", "discord", "steam", "telegram", "yazi" ]
    enable_builtin_templates = true
    enable_community_templates = true

[wallpaper]
directory = "/home/artemii/.config/wallpapers"
directory_dark = "/home/artemii/.config/wallpapers/dark"
directory_light = "/home/artemii/.config/wallpapers/light"
edge_smoothness = 0.30000001192092896
enabled = true
fill_color = ""
fill_mode = "crop"
per_monitor_directories = false
transition = [ "disc", "fade", "honeycomb", "stripes", "wipe", "zoom" ]
transition_duration = 1500.0
transition_on_startup = false

    [wallpaper.automation]
    enabled = false
    interval_minutes = 0
    order = "random"
    recursive = true

[weather]
address = "Pyatigorsk"
auto_locate = false
effects = false
enabled = true
refresh_minutes = 30
unit = "metric"

[widget.active_window]
icon_size = 14.0
max_length = 260.0
min_length = 80.0
title_scroll = "none"
type = "active_window"

[widget.control-center]
glyph = "settings"
type = "control-center"

[widget.cpu]
stat = "cpu_usage"
type = "sysmon"

[widget.date]
format = "{:%a %d %b}"
type = "clock"

[widget.input_volume]
device = "input"
type = "volume"

[widget.keyboard_layout]
cycle_command = ""
hide_when_single_layout = false
type = "keyboard_layout"

[widget.lock_keys]
display = "short"
hide_when_off = false
show_caps_lock = true
show_num_lock = true
show_scroll_lock = false
type = "lock_keys"

[widget.media]
art_size = 16.0
max_length = 220.0
min_length = 80.0
title_scroll = "none"
type = "media"

[widget.network_rx]
stat = "net_rx"
type = "sysmon"

[widget.network_tx]
stat = "net_tx"
type = "sysmon"

[widget.output_volume]
device = "output"
type = "volume"

[widget.ram]
stat = "ram_used"
type = "sysmon"

[widget.spacer]
type = "spacer"

[widget.temp]
stat = "cpu_temp"
type = "sysmon"
